### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeremygottfried**
I am proposing a simple step by step tutorial to run the VoiceTest example

### CODE REVIEW

**Comment by tejachundru** [comment]
There are the steps are needed if you create app using `create-react-native-app`.

If you use using `react-native init YourAppName`,these steps are not needed are not needed.

**Comment by sibelius** [comment]
you can just go to https://github.com/wenkesj/react-native-voice/tree/master/VoiceTest and run it

**Comment by jeremygottfried** [comment]
Not true last time I checked

**Comment by sibelius** [comment]
fixed example here https://github.com/wenkesj/react-native-voice/pull/135

**Pull request closed without merging**
