### PR TITLE
Fixes #40 - Android doesnt support locale of "en"

### LINKED ISSUE #40: 4/error from server
I am using Android 6 for testing. However after I do `Voice.start()` and it returns `undefined` I then speak and it trigger `onSpeechError` with `error` being `{ message: "4/error from server" }`.

May you please advise.

Here is my component:

```
// @flow

import React, { PureComponent } from 'react'
import { Button, PermissionsAndroid, Text, View } from 'react-native'
import Voice from 'react-native-voice'

import styles from './styles'

class VoiceButton extends PureComponent {
    state = {
        isRecording: false,
        partial: '',
        result: ''
    }

    componentDidUpdate(propsOld, stateOld) {
        const { isRecording } = this.state;
        const { isRecording:isRecordingOld } = stateOld;

        if (isRecording !== isRecordingOld) {
            if (isRecording) this.voiceStart()
            else this.voiceStop();
        }
    }
    componentWillUnmount() {
        this.voiceDestroy();
    }
    render() {
        const { partial, result, isRecording } = this.state;
        return (
            <View style={styles.container}>
                <View>
                    <Text>{isRecording ? 'Listening...' : 'Press and hold button then speak'}</Text>
                </View>
                <Button title="Record" onPress={this.handlePress} />
                <View>
                    <Text>PARTIAL RESULTS</Text>
                    <Text>{partial}</Text>
                </View>
                <View>
                    <Text>RESULT</Text>
                    <Text>{result}</Text>
                </View>
            </View>
        )
    }

    handlePress = () => this.setState(({ isRecording }) => ({ isRecording:!isRecording }))

    voiceStart = async () => {
        this.setState(() => ({ result:'', partial:'' }));
        console.log('Voice.isAvailable():', await Voice.isAvailable());

        try {
            const didGrant = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO, { title:'Microphone Permission', message:'Enter the Gunbook needs access to your microphone so you can search with voice.' });
            console.log('didGrant:', didGrant);
            if (didGrant !== PermissionsAndroid.RESULTS.GRANTED) {
                console.log('you denied permission');
                return;
            }
        } catch(err) {
            console.error('failed getting permission, err:', err.message);
            return;
        }

        // Voice.onSpeechStart = this.handleSpeechStart;
        // Voice.onSpeechRecognized = this.handleSpeechRecognized;
        // Voice.onSpeechEnd = this.handleSpeechEnd;
        Voice.onSpeechError = this.handleSpeechError;
        Voice.onSpeechResults = this.handleSpeechResults;
        Voice.onSpeechPartialResults = this.handleSpeechPartialResults;
        // Voice.onSpeechVolumeChanged = this.handleSpeechVolumeChanged;
        try {
            const started = await Voice.start('en');
            console.log('started:', started);
        } catch(err) {
            console.error('Failed to start, err:', err);
        }
    }
    voiceStop = async () => {
        try {
            const stopped = await Voice.stop();
            console.log('stopped:', stopped);
        } catch(err) {
            console.error('Failed to stop, err:', err);
        }
    }
    voiceCancel = async () => {
        try {
            await Voice.cancel();
        } catch(err) {
            console.error('Failed to cancel, err:', err);
        }
    }
    voiceDestroy = async () => {
        try {
            const destroyed = await Voice.destroy();
            console.log('destroyed:', destroyed);
            Voice.removeAllListeners(destroyed);
        } catch(err) {
            console.error('Failed to destroy, err:', err);
        }

    }

    // handleSpeechStart =
    // handleSpeechRecognized =
    // handleSpeechEnd =
    handleSpeechError = ({ error }) => console.error('speech recording error:', error);
    handleSpeechResults = ({ value }) => this.setState(() => ({ result:value }));
    handleSpeechPartialResults = ({ value }) => this.setState(() => ({ partial:value }));
}

export default VoiceButton

```

### PR DESCRIPTION
**Pull request by Noitidart**
Fixes https://github.com/wenkesj/react-native-voice/issues/40

### CODE REVIEW

**Comment by ohtangza** [comment]
To be more accurate, could you clarify this work both for iOS and Android or one of these if you have some time? It seems that Apple uses `en_US` for the same identifier (ref: 
https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html). Providing reference for Locale will help other devs a lot :)

**Comment by ohtangza** [comment]
@Noitidart I merged it, and add new issue #41 in regards to my comment.

**Comment by Noitidart** [comment]
Oops I missed your message. I tested this on Android, I didn't test on iOS.

**Comment by ohtangza** [comment]
@Noitidart If you have an access to ios resources, it would be really appreciated to resolve #41 as well. If not, I might take care of this, a bit later.

**Pull request merged**
