### PR TITLE
Only set voiceEmitter const on ios or android to avoid resolution errors in web

### PR DESCRIPTION
**Pull request by tdonia**
This is a tiny one but solves an annoying "Not a constructor" webpack resolution issue in the browser.

Thanks for building this!

### CODE REVIEW

**Comment by ohtangza** [comment]
I want to give you a quick feedback, however, I'm not familiar with webpack.

@wenkesj @rudiedev6 Anyone else who can review this simple pull request?

**Comment by tdonia** [comment]
Thanks @ohtangza! If it helps for context, I encountered this on a web-based create-react-app that uses react-native for iOS/Android.  The web version uses the SpeechRecognition API so there's a conditional that selects either a react-native-voice or web component based on platform.  As long as the react-native-voice is imported, even if it's not being rendered, webpack tries find that emitter which of course doesn't exist or inadvertently collides, hence the need for this PR.

**Comment by ohtangza** [comment]
@tdonia Just for the last confirmation, so you are importing this library in the environment other than RN, is it correct? Then, could you please add a line of comment what it does, so that it does not confuse the RN users? This will provide more maintainability of this library :) Please understand this library is primarily designed for RN use case. 

After that, I will merge it as soon as possible. Thanks for your effort!

**Comment by tdonia** [comment]
Thank you @ohtangza -- I've added a comment.  Let me know if that's OK.

**Comment by ohtangza** [comment]
@tdonia Thank you for your prompt response. I just merged your work!

**Pull request merged**
